api_platform:
  title: StreamVibe API
  version: 1.0.0
  enable_swagger: true
  enable_swagger_ui: true
  enable_re_doc: false

  mapping:
    paths:
      - '%kernel.project_dir%/src/Infrastructure/ApiPlatform'

  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

  openapi:
    swagger_ui_extra_configuration:
      persistAuthorization: true