name: "Deploy to Platform.sh"

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: StreamVibe
    env:
      PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORM_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Platform.sh CLI
        run: | 
          curl -sS https://platform.sh/cli/installer | php
          echo "$HOME/.platformsh/bin" >> $GITHUB_PATH

      # Configure the project in CLI (insert the project ID)
      - name: Set Platform.sh project
        run: ~/.platformsh/bin/platform project:set-remote ${{ secrets.PLATFORMSH_PROJECT_ID }}

      # Generate SSH certificate and add host into known_hosts
      - name: Load Platform.sh SSH certificate
        run: ~/.platformsh/bin/platform ssh-cert:load --new --yes
      - name: Add Platform.sh SSH to known_hosts
        run: |
          ssh-keyscan -t rsa ${{ secrets.PLATFORMSH_SSH_HOST }} >> ~/.ssh/known_hosts

      # Push to environment wished (master or develop)
      - name: Push to Platform.sh
        run: ~/.platformsh/bin/platform push -p ${{ secrets.PLATFORMSH_PROJECT_ID }} -e ${{ github.ref_name }} -f
